### ISSUE TITLE
Discord should be more prominent on the website

### ISSUE THREAD

**Issue by BatmanSprawl** [BurbSec/Burbsec.com-Website#21]
With the goal of growing the Burbsec discord and promoting it as a space for all, it would make more sense to have it be promoted just like the burbsec meetups (or at least more visible than just a link)

**Comment by TechByTom** [comment]
A BurbsecOnline "venue" or something to that effect might make it a bit more prominent (but keep the current link too)?

**Comment by Mr-Sprawl** [comment]
Possibly, More created this because Johnny asked in discord. I actually don't know how to get to the discord from the website after looking again. A section (or "Venue" like you called it) in the same style as our chicagoland/ireland/sigs with the discord could prove helpful but Johnny might have different ideas. The roadsign with burbsec | gg and then the discord app might help.

**Comment by johnnyxmas** [comment]
Honestly maybe right under "I wanna go!" have another button that's "Join our Discord!" 

Or, have a section above Chicagoland for the Discord and Slack?

**Comment by johnnyxmas** [comment]
Fixed under [f5a7986](https://github.com/BurbSec/Burbsec.com-Website/commit/f5a7986397ef91a396b0efd455dd2adb32d93a98)
